.onLoad <- function(libname, pkgname){
  utils::globalVariables(c('q_mm_day', 'q_mm_day_aggregate',
                           'day_of_year', 'day', 'month', 'year',
                           'gauge_id',
                           'colorBin',
                           'percentile',
                           'Q_min',
                           'Q_10%',
                           'Q_25%',
                           'Q_75%',
                           'Q_90%',
                           'Q_max',
                           'Q_current_year',
                           'object_id',
                           'pr',
                           'tasmin',
                           'tasmax',
                           'hurs',
                           'forecast_hour',
                           'time',
                           'variable',
                           'value',
                           'discharge_spec_obs'))
}
